apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hb-test-2
  annotations:
    scenarios.ai.sap.com/description: "hb test 2"
    scenarios.ai.sap.com/name: "hb-dataline-exec2"
    executables.ai.sap.com/description: "Test pipeline for hb"
    executables.ai.sap.com/name: "training-hb2"
  labels:
    scenarios.ai.sap.com/id: "hb-dataline-execid2"
    ai.sap.com/version: "2.0"
spec:
  imagePullSecrets:
    - name: hack2build
  entrypoint: hbpipeline
  templates:
  - name: hbpipeline
    steps:
    - - name: fdpredictor
        template: fdcodeblock0
  - name: fdcodeblock0
    metadata:
      labels:
        ai.sap.com/resourcePlan: starter
    inputs: {}
    outputs:
      artifacts:
        - name: fdmodel
          globalName: fdmodel
          path: /app/model/
          archive:
            none: {}
    container:
      image: docker.io/valaysalve/hb:01
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/h2b.py"
