apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hb-test-1
  annotations:
    scenarios.ai.sap.com/description: "hb test 1"
    scenarios.ai.sap.com/name: "hb-dataline-exec"
    executables.ai.sap.com/description: "Test pipeline for hb"
    executables.ai.sap.com/name: "training-hb"
  labels:
    scenarios.ai.sap.com/id: "hb-dataline-execid"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: hacktobuild
  entrypoint: hbpipeline
  templates:
  - name: hbpipeline
    steps:
    - - name: fdpredictor
        template: fdcodeblock0
  - name: fdcodeblock0
    metadata:
          labels:
              ai.sap.com/resourcePlan: starter
    container:
      image: docker.io/valaysalve/reelmatching:01
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/Reel_Matching.py"
